Repository rpm-software-management/rpm, pull requests merged in 2019-05, with the labels that each got.

#696 Fix recently introduced uninitialized variable warning in rpm2archive
  rpm2archive.c
Labels: REGRESSION

#694 Fix memory reading in the expansion of an unfinished macro "{%!"
  rpmio/macro.c
Labels: bug

#699 Fix memleak in rpmfcApplyInternal() in standalone operation (eg rpmdeps)
  build/rpmbuild_internal.h
  build/rpmfc.c
  build/spec.c
Labels: bug

#692 Adopt compiler flags related enhancements from Fedora
  macros.in
Labels: RFE

#697 Remove nonexistent macro "Q" from the table of builtin macros
  rpmio/macro.c
Labels: bug

#693 Sanitize spec tag macro creation
  build/parsePreamble.c
Labels: bug, cleanup

#704 Only switch to userns-root if we actually need it for chroot()
  lib/rpmchroot.c
Labels: REGRESSION

#698 Dependency generator optimization and cleanup
  build/rpmfc.c
Labels: cleanup

#705 Fix use-after-free introduced in 0f21bdd0d7b2c45564ddb5a24bbebd530867…
  rpmio/rpmfileutil.c
Labels: REGRESSION

#706 Fix packages getting erased on failed update with dnf (RhBug:1620275)
  lib/depends.c
Labels: bug

#709 Fix regression causing patch/source tags leaking to other macros
  build/parsePreamble.c
  tests/data/SPECS/foo.spec
  tests/rpmspec.at
Labels: REGRESSION

#720 Include dynamic buildrequires test material in dist tarballs
  tests/Makefile.am
Labels: REGRESSION
