Repository rpm-software-management/rpm, pull requests merged in 2019-07, with the labels that each got.

#784 Print newline after "failed to load macro file" error is emitted
  rpmio/macro.c
Labels: bug

#783 Raise an error if reading a file during rpmbuild fails (#776)
  build/files.c
Labels: bug

#778 Parse multiline conditional and %include parameters correctly (#775)
  build/parseSpec.c
  tests/Makefile.am
  tests/data/SPECS/ifmultiline.spec
  tests/rpmmacro.at
Labels: bug

#786 Describe conditionally expanded macros in manual
  doc/manual/macros
Labels: documentation

#803 Fix off-by-one in hdrblobGet() making last entry unreachable (RhBug:1…
  lib/header.c
Labels: REGRESSION
