Repository rpm-software-management/rpm, pull requests merged in 2019-06, with the labels that each got.

#731 Include file capability test material in dist tarballs
  tests/Makefile.am
Labels: REGRESSION

#736 Remove unused target variable from rpmspec.c
  rpmspec.c
Labels: cleanup

#734 Fix --signfiles regression (#723)
  sign/rpmsignfiles.c
Labels: REGRESSION

#737 Fix bogus if-condition in find-debuginfo.sh (#735)
  scripts/find-debuginfo.sh
Labels: bug

#749 Don't fail build trying to kill a non-existent process (RhBug:1720143)
  macros.in
Labels: REGRESSION

#748 Drop bogus condition from header index allocation
  lib/header.c
Labels: cleanup

#753 Implement %dnl (discard to next line) macro primitive for comment use
  doc/manual/macros
  rpmio/macro.c
  tests/data/macros.testfile
  tests/rpmmacro.at
Labels: RFE

#758 Fix build with --disable-openmp
  build/parseSpec.c
  configure.ac
Labels: bug

#765 Use newline as a delimiter to avoid xargs messing up file names with …
  scripts/brp-strip-static-archive
Labels: REGRESSION
