Repository rpm-software-management/rpm, pull requests merged in 2019-08, with the labels that each got.

#805 Fix memleak during transaction verify step in the NOKEY case.
  lib/transaction.c
Labels: bug

#767 Add a testcase for filenames with special characters in them
  tests/Makefile.am
  tests/data/SPECS/weirdnames.spec
  tests/rpmbuild.at
Labels: test

#816 Fix segfault regression on empty script or description at end of spec
  build/parseDescription.c
  build/parseScript.c
  tests/Makefile.am
  tests/data/SPECS/mini.spec
  tests/rpmbuild.at
Labels: REGRESSION

#819 Add a dummy line to CI setup to allow controlling dnf gpgcheck per build
  ci/Dockerfile
Labels: test

#818 Restore strict order of build scriptlet stdout/stderr output (#794)
  build/build.c
  build/files.c
  build/rpmbuild_internal.h
  build/rpmfc.c
Labels: REGRESSION, cleanup

#825 Remove unused variable id in find-debuginfo.sh
  scripts/find-debuginfo.sh
Labels: cleanup, debuginfo

#823 Cap number of threads on 32bit platforms, add a tunable (RhBug:1729382)
  build/parseSpec.c
  platform.in
Labels: REGRESSION
