Repository rpm-software-management/rpm, pull requests merged in 2022-11, with the labels that each got.

#2245 Axe man page translations
  docs/man/fr/rpm.8.md
  docs/man/ja/rpm.8.md
  docs/man/ja/rpm2cpio.8.md
  docs/man/ja/rpmbuild.8.md
  docs/man/ja/rpmgraph.8.md
  docs/man/ko/rpm.8.md
  docs/man/ko/rpm2cpio.8.md
  docs/man/pl/gendiff.1.md
  docs/man/pl/rpm.8.md
  docs/man/pl/rpm2cpio.8.md
  docs/man/pl/rpmbuild.8.md
  docs/man/pl/rpmdeps.8.md
  docs/man/pl/rpmgraph.8.md
  docs/man/ru/rpm.8.md
  docs/man/ru/rpm2cpio.8.md
  docs/man/sk/rpm.8.md
Labels: cleanup

#2260 Remember to set include directories from pkgconfig for Lua
  build/CMakeLists.txt
  lib/CMakeLists.txt
  rpmio/CMakeLists.txt
Labels: build

#2267 Eliminate remaining %{u2p:...} uses
  macros.in
Labels: cleanup

#2268 CI hardening tweaks
  ci/Dockerfile
  ci/Dockerfile.debian
Labels: build

#1485 Dynamic Spec generation
  build/build.c
  build/parsePrep.c
  build/parseSpec.c
  build/rpmbuild_internal.h
  docs/CMakeLists.txt
  docs/manual/buildprocess.md
  docs/manual/dynamic_specs.md
  docs/manual/index.md
  macros.in
  tests/data/SPECS/dynamic.spec
  tests/rpmbuild.at
  tests/rpmspec.at
Labels: RFC

#2290 Add some basic tests for OpenPGP v3 signatures
  tests/data/RPMS/hello-2.0-1.x86_64-v3-signed.rpm
  tests/rpmsigdig.at
Labels: test

#2295 Bump CI to Fedora 37
  ci/Dockerfile
Labels: test

#2301 Use cmake imported targets to let it sort out the compiler flag details
  CMakeLists.txt
  build/CMakeLists.txt
  lib/CMakeLists.txt
  plugins/CMakeLists.txt
  rpmio/CMakeLists.txt
  sign/CMakeLists.txt
Labels: build
