Repository rpm-software-management/rpm, pull requests merged in 2022-01, with the labels that each got.

#1862 Fix a memleak in ndb from opened but not closed dbis.
  lib/backend/ndb/glue.c
Labels: bug

#1022 Allow qualifiers like pre, post, preun, ... for weak dependencies, too
  build/parsePreamble.c
Labels: RFE

#1854 Skip recorded symlinks in --setperms (RhBug:1900662)
  rpmpopt.in
Labels: DRAGONS
