Repository rpm-software-management/rpm, pull requests merged in 2023-01, with the labels that each got.

#2341 Generate Python egg-info from automake builds (4.18.x)
  configure.ac
  python/Makefile.am
  python/rpm.egg-info.in
Labels: python

#2300 Add --generate-subpackages to find_lang.sh
  macros.in
  scripts/find-lang.sh
  tests/data/SPECS/find-lang-test.spec
  tests/populate
  tests/rpmbuild.at
Labels: RFC

#2357 Try telling cmake that the project needs to be built before testing
  tests/CMakeLists.txt
Labels: bug, build

#2358 Fix macro scoping level on re-entry from %[] expresssion (#2354)
  rpmio/macro.c
  tests/rpmmacro.at
Labels: bug
