Repository rpm-software-management/rpm, pull requests merged in 2023-11, with the labels that each got.

#2746 Refactor %__file_lineno management into an auxiliary macro
  build/parseSpec.c
  rpmio/macro.c
Labels: optimization

#2723 Move OpenSSL code to newer API
  INSTALL
  rpmio/rpmpgp_legacy/CMakeLists.txt
  rpmio/rpmpgp_legacy/digest_openssl.c
Labels: crypto

#2759 Fix sbit removal if fchmodat() doesn't support AT_SYMLINK_NOFOLLOW
  lib/fsm.c
  tests/rpme.at
Labels: bug

#2770 Fix integer overflow in memory calculations on 32bit systems
  rpmio/macro.c
Labels: bug
