Repository rpm-software-management/rpm, pull requests merged in 2023-12, with the labels that each got.

#2802 Don't include git refs in ChangeLog
  CMakeLists.txt
Labels: cleanup, build

#2804 Build all manuals regardless of enabled features
  docs/man/CMakeLists.txt
Labels: build

#2806 Print full path if file removal fails
  lib/fsm.c
Labels: bug

#2814 Don't warn about missing user/group on skipped files
  lib/fsm.c
Labels: REGRESSION

#2818 Fix regression in Lua scriptlet runaway child detection
  rpmio/rpmlua.c
  tests/rpmmacro.at
Labels: REGRESSION, lua
