Repository rpm-software-management/rpm, pull requests merged in 2024-05, with the labels that each got.

#3079 Simplify rpmfi replaced sized management
  lib/rpmfi.c
Labels: cleanup

#3080 Replace the annoying keyid stash with an STL set
  lib/rpmfi.c
Labels: cleanup

#3085 Add proper logic for debuginfo enablement
  installplatform
  macros.in
  platform.in
  tests/data/SPECS/specstep.spec
  tests/data/macros.debug
  tests/rpmbuild.at
Labels: highlight

#3095 Free old cookie value to prevent a memory leak
  build/pack.c
Labels: bug

#3101 Clean up applyAttr() and rpmfcHelper() interaction
  build/rpmfc.c
Labels: cleanup

#3124 Make --build-in-place much less of a hack and also, work
  build/parsePrep.c
  tests/rpmbuild.at
  tools/rpmbuild.c
Labels: REGRESSION

#3127 Fix incomplete header on plain src.rpm build modes regression
  tests/rpmbuild.at
  tools/rpmbuild.c
Labels: REGRESSION

#3134 Fix regression on subpackage debuginfo RPMTAG_SOURCERPM missing
  build/files.c
Labels: REGRESSION

#3137 Fix a %buildroot regression on an early %__spec_install_pre %global o…
  macros.in
  tests/data/SPECS/install-hack.spec
  tests/rpmbuild.at
Labels: REGRESSION
