Repository rpm-software-management/rpm, pull requests merged in 2024-02, with the labels that each got.

#2883 Pass arg2 to file trigger scripts
  docs/manual/file_triggers.md
  lib/psm.c
  lib/rpmtriggers.c
  lib/rpmtriggers.h
  lib/transaction.c
  tests/data/SPECS/filetriggers.spec
  tests/rpmscript.at
Labels: RFE, transaction, highlight

#2405 Allow to specify a default for bcond features in a macro file
  docs/manual/conditionalbuilds.md
  macros.in
  tests/rpmbuild.at
Labels: RFE, packaging

#2898 Run build scriptlets with closed stdin to enforce unattended builds
  build/rpmfc.c
  tests/data/SPECS/interact.spec
  tests/rpmbuild.at
Labels: bug

#2900 Drop erroneous BYPRODUCTS uses from the cmake files
  CMakeLists.txt
  tools/CMakeLists.txt
Labels: build

#2901 Use Ninja-compatible syntax for passing TESTOPTS
  tests/CMakeLists.txt
  tests/README.md
Labels: build

#2902 Let eBPF ELF files be packaged in noarch packages
  build/rpmfc.c
  tests/data/SPECS/bpf.spec
  tests/data/misc/bpf.o
  tests/rpmbuild.at
Labels: bug

#2913 Implement --json query format
  docs/man/rpm.8.md
  include/rpm/rpmtd.h
  lib/formats.c
  lib/headerfmt.c
  rpmpopt.in
  tests/rpmquery.at
Labels: RFE, highlight

#2915 Generate rpmtests.at automatically to avoid redundant book-keeping
  tests/CMakeLists.txt
  tests/rpmtests.at
Labels: cleanup, test
