Repository rpm-software-management/rpm, pull requests merged in 2024-03, with the labels that each got.

#2933 Expose build time to package build scriptlets via $RPM_BUILD_TIME
  build/build.c
  docs/manual/spec.md
Labels: RFE, packaging

#2947 Remove perl dependency generators from the repo
  scripts/CMakeLists.txt
  scripts/perl.prov
  scripts/perl.req
Labels: generator, highlight

#2958 Fix dependency generators sometimes dying with SIGPIPE
  build/rpmfc.c
Labels: REGRESSION

#2940 Issue a warning when passing arguments to non-parametric macros
  rpmio/macro.c
  tests/rpmmacro.at
Labels: RFE

#2885 Introduce an rpm-controlled per-build directory
  build/build.c
  build/files.c
  build/parsePreamble.c
  build/parseSpec.c
  build/policies.c
  build/rpmbuild_internal.h
  build/spec.c
  docs/manual/buildprocess.md
  docs/manual/dynamic_specs.md
  include/rpm/rpmbuild.h
  macros.in
  tests/data/SPECS/simple.spec
  tests/rpmbuild.at
  tests/rpmspec.at
  tools/rpmbuild.c
Labels: packaging, highlight

#2973 Work around ASAN incompatibility with GH runner image >= 20240310.1.0
  .github/workflows/linux.yml
Labels: test

#2978 Sqlite backend spring cleaning
  lib/backend/sqlite.c
Labels: cleanup

#2981 Bunch of docs formatting cosmetics
  docs/manual/queryformat.md
  docs/manual/spec.md
Labels: documentation

#2984 Allow building rpm without OpenPGP support
  CMakeLists.txt
  INSTALL
  rpmio/CMakeLists.txt
  rpmio/digest_libgcrypt.c
  rpmio/digest_openssl.c
  rpmio/rpmpgp_dummy.c
  rpmio/rpmpgp_legacy/CMakeLists.txt
  rpmio/rpmpgp_legacy/digest_libgcrypt.c
  rpmio/rpmpgp_legacy/digest_openssl.c
  tests/CMakeLists.txt
  tests/rpmdb.at
  tests/rpmi.at
  tests/rpmpgp.at
  tests/rpmpython.at
  tests/rpmquery.at
  tests/rpmsigdig.at
  tests/rpmvfylevel.at
Labels: crypto

#2991 Add a note about --setenv to test README
  tests/README.md
Labels: documentation

#3000 Lump version comparison tests into a single test-group
  tests/rpmvercmp.at
Labels: cleanup, test
